const express=require("express")
const server=express()
//const morgan=require("morgan")
const logger=require("./middleware/logger")
const bp=require("body-parser")
server.use(bp.json())
//server.use(morgan('tiny'))
server.use(logger)
const todoRoutes=require("./routes/todoRoutes")
const cmRoutes=require("./routes/cmanager")
const signup=require("./routes/Signup")
const signin=require("./routes/Signin")
const protected=require("./routes/protected")
const createContact=require("./routes/createContact")
server.use("/todo",todoRoutes)
server.use("/",cmRoutes)
server.use("/",signup)
server.use("/",signin)
server.use("/",protected)
server.use("/",createContact)
server.listen(3001,()=>console.log("server has started at port no : 3001"))